title: SQL Server Always On Puppet module
description: Puppet module installing a fully working SQL Server Always On cluster including : SPN creation, SQL server installation and initial configuration, windows failover cluster and SQL Always On Availability Group creation.
google_site_verification: R71XDERzPOp9lUudi8X6iKrpcoIgDG_1HzRMz_TMaDY
google_analytics: UA-12767493-6
theme: jekyll-theme-slate
show_downloads: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-mentions
jekyll-mentions:
  base_url: http://www.virtualdesktopdevops.com/puppet-modules/sql-server-alwayson.html
